# Generated by Django 4.0.5 on 2022-06-18 12:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200, verbose_name='نام مشتری')),
                ('last_name', models.CharField(max_length=200, verbose_name='تخلص')),
                ('phone_number1', models.CharField(max_length=15, verbose_name='شماره تماس')),
                ('phone_number2', models.CharField(blank=True, max_length=15, null=True, verbose_name='شماره واتساپ یا تلگرام')),
                ('address', models.TextField(verbose_name='آدرس مشتری')),
                ('created', models.DateField(verbose_name='تاریخ مراجعه')),
            ],
            options={
                'verbose_name': 'مشتری',
                'verbose_name_plural': 'مشتریان',
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200, verbose_name='نام')),
                ('last_name', models.CharField(max_length=200, verbose_name='تخلص')),
                ('phone_number', models.CharField(max_length=20, verbose_name='شماره تماس')),
                ('address', models.CharField(max_length=200, verbose_name='آدرس خانه')),
                ('position', models.CharField(max_length=200, verbose_name='نوع کارمند')),
                ('salary', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='معاش')),
                ('total_work', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='مجموع کارکرد مشتری')),
                ('emp_type', models.CharField(choices=[('کونترات', 'کونترات'), ('ماهوار', 'ماهوار')], max_length=20, verbose_name='نوعیت معاش')),
                ('created_at', models.DateField(verbose_name='تاریخ استخدام')),
            ],
            options={
                'verbose_name': 'کارمند',
                'verbose_name_plural': 'کارمندان',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('جدید', 'جدید'), ('در حال اجرا', 'در حال اجرا'), ('تمام', 'تمام')], default='جدید', max_length=20, verbose_name='وضعیت فرمایش')),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='مقدار باقی مانده')),
                ('order_date', models.DateField(verbose_name='تاریخ فرمایش')),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='factory.customer', verbose_name='نام مشتری')),
            ],
            options={
                'verbose_name': 'فرمایش',
                'verbose_name_plural': 'فرمایشات',
            },
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=200, verbose_name='نام محصول')),
                ('sample_image', models.ImageField(blank=True, null=True, upload_to='category/images', verbose_name='نمونه عکس')),
                ('created', models.DateField(verbose_name='تاریخ ایجاد')),
            ],
            options={
                'verbose_name': 'کتگوری محصولات',
                'verbose_name_plural': 'کتگوری محصولات',
            },
        ),
        migrations.CreateModel(
            name='ReceiveMoney',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receive_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='مقدار اخذ شده')),
                ('price_unit', models.CharField(choices=[('افغانی', 'افغانی'), ('دالر', 'دالر'), ('کلدار', 'کلدار'), ('تومان', 'تومان')], default='دالر', max_length=20, verbose_name='واحد پول')),
                ('remain_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='مقدار باقی مانده')),
                ('receive_date', models.DateField(verbose_name='تاریخ اخذ پول')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='factory.order', verbose_name='دریافتی از مشتری')),
            ],
            options={
                'verbose_name': 'دریافتی',
                'verbose_name_plural': 'دریافتی ها',
            },
        ),
        migrations.CreateModel(
            name='OrderDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('height', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='بلندی محصول')),
                ('width', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='عرض محصول')),
                ('depth', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='عمق محصول')),
                ('direction', models.CharField(blank=True, choices=[('راست', 'راست'), ('چپ', 'چپ')], default='راست', max_length=30, null=True, verbose_name='سمت')),
                ('qty', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='تعداد یا متراژ')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='قیمت')),
                ('price_unit', models.CharField(choices=[('افغانی', 'افغانی'), ('دالر', 'دالر'), ('کلدار', 'کلدار'), ('تومان', 'تومان')], default='افغانی', max_length=20, verbose_name='واحد پول')),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='مجموع')),
                ('description', models.CharField(help_text='ذکر موارد خاص', max_length=255, verbose_name='توضیحات')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='factory.order', verbose_name='فرمایش')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='factory.productcategory', verbose_name='کتگوری محصول')),
            ],
            options={
                'verbose_name': 'جزییات فرمایش',
                'verbose_name_plural': 'جزییات فرمایش',
            },
        ),
        migrations.CreateModel(
            name='EmployeeWork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='تعداد کار')),
                ('fees', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='دستمزد فی واحد کار')),
                ('done', models.BooleanField(default=False, verbose_name='تکمیل شده')),
                ('assigned_date', models.DateField(blank=True, null=True, verbose_name='تاریخ کار')),
                ('employee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='factory.employee', verbose_name='کارمند')),
                ('order_detail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='factory.orderdetail', verbose_name='کارکرد')),
            ],
            options={
                'verbose_name': 'کارکرد کارمند',
                'verbose_name_plural': 'کارکرد کارمند',
            },
        ),
        migrations.CreateModel(
            name='EmployeeSalaryPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paid_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='مساعده')),
                ('paid_at', models.DateField(verbose_name='تاریخ پرداخت')),
                ('employee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='factory.employee', verbose_name='کارمند')),
                ('order_detail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='factory.orderdetail', verbose_name='بابت کار')),
            ],
            options={
                'verbose_name': 'حسابات کارمند',
                'verbose_name_plural': 'حسابات کارمند',
            },
        ),
    ]
