# Generated by Django 4.0.5 on 2022-06-15 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factory', '0002_customer_created'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'verbose_name': 'مشتری', 'verbose_name_plural': 'مشتریان'},
        ),
        migrations.AlterField(
            model_name='customer',
            name='address',
            field=models.TextField(verbose_name='آدرس مشتری'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='created',
            field=models.DateField(verbose_name='تاریخ مراجعه'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='first_name',
            field=models.CharField(max_length=200, verbose_name='نام مشتری'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='last_name',
            field=models.CharField(max_length=200, verbose_name='تخلص'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone_number1',
            field=models.CharField(max_length=15, verbose_name='شماره تماس'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone_number2',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='شماره واتساپ یا تلگرام'),
        ),
    ]
