# Generated by Django 4.0.5 on 2022-06-18 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factory', '0002_remove_employeesalarypayment_order_detail_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeesalarypayment',
            name='remain_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='باقی مانده'),
        ),
    ]
