# Generated by Django 4.0.5 on 2022-06-15 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factory', '0003_alter_customer_options_alter_customer_address_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=200, verbose_name='نام محصول')),
                ('sample_image', models.ImageField(blank=True, null=True, upload_to='category/images', verbose_name='نمونه عکس')),
                ('created', models.DateField()),
            ],
            options={
                'verbose_name': 'کتگوری محصولات',
                'verbose_name_plural': 'کتگوری محصولات',
            },
        ),
    ]
