# Generated by Django 4.0.5 on 2022-06-19 18:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('factory', '0003_employeesalarypayment_remain_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeesalarypayment',
            name='employee',
        ),
        migrations.RemoveField(
            model_name='employeesalarypayment',
            name='work',
        ),
        migrations.RemoveField(
            model_name='employeework',
            name='employee',
        ),
        migrations.RemoveField(
            model_name='employeework',
            name='order_detail',
        ),
        migrations.AlterField(
            model_name='orderdetail',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='factory.order', verbose_name='فرمایش دهنده'),
        ),
        migrations.DeleteModel(
            name='Employee',
        ),
        migrations.DeleteModel(
            name='EmployeeSalaryPayment',
        ),
        migrations.DeleteModel(
            name='EmployeeWork',
        ),
    ]
