# Generated by Django 4.0.5 on 2022-06-15 06:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('factory', '0004_productcategory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcategory',
            name='created',
            field=models.DateField(verbose_name='تاریخ ایجاد'),
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('height', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='قد')),
                ('width', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='بر')),
                ('depth', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='عمق')),
                ('direction', models.CharField(blank=True, choices=[('راست', 'راست'), ('چپ', 'چپ')], default='راست', max_length=30, null=True)),
                ('quantity', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='مقدار / تعداد')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='قیمت فی واحد')),
                ('price_unit', models.CharField(choices=[('افغانی', 'افغانی'), ('دالر', 'دالر'), ('کلدار', 'کلدار'), ('تومان', 'تومان')], max_length=20, verbose_name='واحد پول')),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='مجموع')),
                ('remain_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='مقدار باقی مانده')),
                ('type', models.CharField(max_length=200, verbose_name='نوعیت کار')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='factory.productcategory', verbose_name='کتگوری محصولات')),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='factory.customer', verbose_name='مشتری')),
            ],
            options={
                'verbose_name': 'فرمایش',
                'verbose_name_plural': 'فرمایشات',
            },
        ),
    ]
