# Generated by Django 4.0.5 on 2022-06-20 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factory', '0004_remove_employeesalarypayment_employee_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='receivemoney',
            name='mark_as_received',
            field=models.BooleanField(default=False, verbose_name='تصفیه شده'),
        ),
    ]
