# Generated by Django 4.0.5 on 2022-06-15 17:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('factory', '0007_remove_order_category_remove_order_customer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='factory.customer', verbose_name='نام مشتری'),
        ),
    ]
