# Generated by Django 4.0.5 on 2022-06-15 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factory', '0009_orderdetail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdetail',
            name='price_unit',
            field=models.CharField(choices=[('افغانی', 'افغانی'), ('دالر', 'دالر'), ('کلدار', 'کلدار'), ('تومان', 'تومان')], default='افغانی', max_length=20, verbose_name='واحد پول'),
        ),
    ]
