# Generated by Django 4.0.5 on 2022-06-15 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factory', '0010_alter_orderdetail_price_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdetail',
            name='qty',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='تعداد یا متراژ'),
        ),
    ]
