# Generated by Django 4.0.5 on 2022-06-15 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factory', '0011_alter_orderdetail_qty'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdetail',
            name='direction',
            field=models.CharField(blank=True, choices=[('راست', 'راست'), ('چپ', 'چپ')], default='راست', max_length=30, null=True, verbose_name='سمت'),
        ),
        migrations.AlterField(
            model_name='orderdetail',
            name='depth',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='عمق محصول'),
        ),
        migrations.AlterField(
            model_name='orderdetail',
            name='height',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='بلندی محصول'),
        ),
        migrations.AlterField(
            model_name='orderdetail',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='قیمت'),
        ),
        migrations.AlterField(
            model_name='orderdetail',
            name='width',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='عرض محصول'),
        ),
    ]
