# Generated by Django 4.0.5 on 2022-06-15 20:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('factory', '0012_orderdetail_direction_alter_orderdetail_depth_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='product',
        ),
        migrations.AddField(
            model_name='orderdetail',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='factory.productcategory', verbose_name='کتگوری محصول'),
        ),
    ]
