# Generated by Django 4.0.5 on 2022-06-16 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factory', '0014_order_amount_alter_orderdetail_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='مجموع پول'),
        ),
    ]
