# Generated by Django 4.0.5 on 2022-06-16 15:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('factory', '0016_alter_order_amount'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReceiveMoney',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receive_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='مقدار اخذ شده')),
                ('receive_date', models.DateTimeField(verbose_name='تاریخ اخذ پول')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='factory.order', verbose_name='فرمایش')),
            ],
            options={
                'verbose_name': 'دریافتی',
                'verbose_name_plural': 'دریافتی ها',
            },
        ),
    ]
