# Generated by Django 4.0.5 on 2022-06-16 15:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('factory', '0017_receivemoney'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receivemoney',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='factory.order', verbose_name='دریافتی از مشتری'),
        ),
        migrations.AlterField(
            model_name='receivemoney',
            name='receive_date',
            field=models.DateField(verbose_name='تاریخ اخذ پول'),
        ),
    ]
