# Generated by Django 4.0.5 on 2022-06-16 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factory', '0018_alter_receivemoney_order_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='receivemoney',
            name='remain_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='مقدار باقی مانده'),
        ),
    ]
