# Generated by Django 4.0.5 on 2022-06-17 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factory', '0019_receivemoney_remain_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='مقدار باقی مانده'),
        ),
    ]
