# Generated by Django 4.0.5 on 2022-06-17 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('factory', '0023_receivemoney_price_unit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receivemoney',
            name='price_unit',
        ),
    ]
