# Generated by Django 4.0.5 on 2022-06-19 19:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('حاضر', 'حاضر'), ('غایب', 'غایب')], default='حاضر', max_length=20, verbose_name='وضعیت')),
                ('delay', models.BooleanField(default=False, verbose_name='تاخیر بیش از نیم ساعت')),
                ('penalty', models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='جریمه بابت تاخیر یا غیر حاضر')),
                ('date', models.DateField(verbose_name='تاریخ')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.employee', verbose_name='مشخصات کارمند')),
            ],
            options={
                'verbose_name': 'حاضری کارمندان',
                'verbose_name_plural': 'حاضری کارمندان',
            },
        ),
    ]
