# Generated by Django 4.0.5 on 2022-06-19 20:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_employeeattendance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeattendance',
            name='penalty',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='مقدار جریمه به افغانی'),
        ),
        migrations.AlterField(
            model_name='employeesalarypayment',
            name='work',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='employee.employeework', verbose_name='بابت کار'),
        ),
    ]
