# Generated by Django 4.0.5 on 2022-06-19 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0003_alter_employeeattendance_penalty_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeesalarypayment',
            name='description',
            field=models.CharField(default='', max_length=200, verbose_name='توضیحات'),
            preserve_default=False,
        ),
    ]
