# Generated by Django 4.0.5 on 2022-06-20 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان مصرف')),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='مقدار کل پرداختی')),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='مقدار پرداخت شده')),
                ('amount_letter', models.CharField(max_length=200, verbose_name='مقدار پرداختی به حروف')),
                ('remain_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='مقدار باقی مانده')),
                ('expenser', models.CharField(max_length=200, verbose_name='مصرف کننده')),
                ('date', models.DateField(verbose_name='تاریخ مصرف')),
            ],
            options={
                'verbose_name': 'مصرف',
                'verbose_name_plural': 'مصارف',
            },
        ),
    ]
