# Generated by Django 4.0.5 on 2022-06-20 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='expense_unit',
            field=models.CharField(choices=[('دالر', 'دالر'), ('افغانی', 'افغانی'), ('کلدار', 'کلدار'), ('تومان', 'تومان')], default='افغانی', max_length=20, verbose_name='واحد پولی'),
        ),
    ]
