# Generated by Django 4.0.5 on 2022-06-20 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0002_expense_expense_unit'),
    ]

    operations = [
        migrations.CreateModel(
            name='Income',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان آمد')),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='مقدار آمد')),
                ('date', models.DateField(verbose_name='تاریخ آمد')),
            ],
            options={
                'verbose_name': 'درآمد',
                'verbose_name_plural': 'ٔدرآمد',
            },
        ),
    ]
